---
- hosts: all
  collections:
    - nginxinc.nginx_core
  tasks:
    - name: Install NGINX App Protect
      ansible.builtin.include_role:
        name: nginx_app_protect
      vars:
        nginx_app_protect_license:
          certificate: <path/to/certificate>
          key: <path/to/key>
        nginx_app_protect_waf_enable: true
        nginx_app_protect_dos_enable: true
        nginx_app_protect_remove_license: false
        nginx_app_protect_install_signatures: true
        nginx_app_protect_install_threat_campaigns: true
