---
- hosts: all
  collections:
    - nginxinc.nginx_core
  tasks:
    - name: Install NGINX Plus
      ansible.builtin.include_role:
        name: nginx
      vars:
        nginx_type: plus
        nginx_license:
          certificate: <path/to/certificate>
          key: <path/to/key>
